# this is the workflow name that will be displayed in the action tab
name: CICD

# Manual click (deliver) whenever user needs
on:
  workflow_dispatch: 

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      steps: echo "code clone from github"   
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker cotainer
        steps: echo "Docker container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
