name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Debug workspace
        run: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la
          echo "COMPOSE FILE:"
          cat docker-compose.yml

      - name: Clean Docker
        run: |
          docker compose down || true
          docker rm -f $(docker ps -aq) || true
          docker system prune -af

      - name: Deploy with Docker Compose
        run: docker compose -f docker-compose.yml up -d
        working-directory: ${{ github.workspace }}