name: Deploy Flask App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy with docker compose
        run: |
          docker compose down || true
          docker system prune -af
          docker compose up -d
        working-directory: ${{ github.workspace }}