name: portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v4
>>>>>>> aeff28c7215c49b488020b4bf93babe96b111681
