name: portfolio

on:
    push:
        branches:[main]

permissions:
      pages: write
      id-token: write
            
jobs:
    deploy:
        run-on: ubuntu-latest

        environment:
            name: github-pages
            url: $ {{ steps.deployment.outputs.page-url}}
        
        steps:
            # get access to your portfolio code via a pre-built action
            # clones or checks out the code where this workflow is written
            - name: checkout code
              uses: action/checkout@v4

              # setup Github pages
              # Step 2 
              -name: Setup the Github pages
               uses: actions/configure-pages@v4

               # static code artifacts
               # Step 3
               - name: upload static files
                 uses: actions/upload-pages-artifact@v4

                 # Make page Live
                 # Step 4

                - name: Deploy the Github pages
                  uses: action/deploy-pages@v4